import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin-Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="flex  overflow-hidden">
          {/* SIDEBAR */}
          <Sidebar />

          {/* PAGE CONTENT */}
          <main className=" flex-1  mt-[100px] min-h-screen overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}




// "use client";
// import { useState } from "react";
// import "./globals.css";
// import Sidebar from "./components/Sidebar";
// import Header from "./components/Header";

// export default function RootLayout({ children }) {
//   const [sidebarOpen, setSidebarOpen] = useState(true);

//   return (
//     <html lang="en">
//       <body className="bg-gray-100">
//         <div className="flex h-screen overflow-hidden">
//           {/* Sidebar */}
//           <Sidebar sidebarOpen={sidebarOpen} />
          
//           {/* Main Content Area */}
//           <div className="flex-1 flex flex-col overflow-hidden">
//             {/* Header */}
//             <Header 
//               sidebarOpen={sidebarOpen} 
//               setSidebarOpen={setSidebarOpen} 
//             />
            
//             {/* Page Content - This is where your pages will render */}
//             <main className={`flex-1 overflow-y-auto transition-all duration-300 ${
//               sidebarOpen ? "ml-72" : "ml-0"
//             } mt-20 bg-gray-50`}>
//               <div className="p-6">
//                 {children}
//               </div>
//             </main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
